### ISSUE TITLE
[UX] - Enable Attribute calculation for different data types

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/refinery#142]
**What would you improve?**
Attribute calculation currently only works for string (TEXT) type. It also triggers the recalculation of the tokenization.

Using different data types as return value will be the first step for upcoming data browser extensions.
Also, tokenization will only be necessary for TEXT & CATEGORY.

**Comment by FelixKirsch** [comment]
**Implementation Plan**
To enhance the attribute calculation a new dropdown will be added to the attribute page which defines the data type of the calculated attribute. The data type must be specified before running the attribute calculation. After running no change of the data type is possible. Therefore, the dropdown on the attribute page and the settings page are disabled if the attribute is in USABLE state. The results of the attribute calculation are written into the database according to the data type. If the data type is TEXT or CATEGORY the tokenization is recalculated, otherwise not. 

Questions:
Do we enable the user to change the data type of added attributes on the settings and the attribute page?

**Frontend**
1. Add a new kern-dropdown with all data types on the attribute-calculation page
2. Set conditions when it should be enabled/disabled
3. Send the mutation for updating the data type

**Backend**
Mutation to update the attribute data type already exists.
1. Tokenize only if data type is TEXT or CATEGORY (1h)
2. Introduce checks if the calculated data type equals the specified data type

**Comment by FelixKirsch** [comment]
https://github.com/code-kern-ai/refinery-ac-exec-env/issues/2
