### ISSUE TITLE
[BUG] - Weak supervision is stuck after docker compose restart

### ISSUE THREAD

**Issue by antopolskiy** [code-kern-ai/refinery#151]
**Describe the bug**
I started weak supervision on my task using multiple heuristics and active learning. Usually it finishes within 3-4 min, but this time it did not (there were no errors). The "Weak supervision" button was deactivated after 15 min:
![image](https://user-images.githubusercontent.com/23148726/197411754-7aee3ae4-adcf-410b-be62-2c6c46fc1d50.png)

I restarted the whole stack with `./stop` and `./start`. However, after that the "Weak supervision" button has not changed, it was same as above, effectively making it impossible to start a new round of Weak supervision.

**To Reproduce**
Steps to reproduce the behavior (I suspect):
1. Start weak supervision
2. Kill the weak supervision container simulating the container dying or hanging in the process 
3. Weak supervision will be forever handing in the UI

**Expected behavior**
On startup it should check if weak supervision is actually running and modify the button accordingly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Chrome
 - Version: latest (1.4.0)

**Comment by jhoetter** [comment]
Hi @antopolskiy, will look into this with the team first thing tomorrow :)

**Comment by DerEchteFeuerpfeil** [comment]
Hey @antopolskiy, I investigated this a bit and although I could not reproduce it, I can probably still resolve this issue for you.

When you press the weak supervision button, a new weak supervision task is created in the database with the initial state of "CREATED". As long as there is a weak supervision task with that state, the button is disabled because it thinks something is still running. 

Now I tried to start a long-running task and kill the weak supervision container in the middle of it but every time I tried so, the state ended up correctly as "FAILED". So my best guess is that something went strangely wrong in your case and it remained on "CREATED". 

![image](https://user-images.githubusercontent.com/57487741/197510575-fd7380ef-db39-4f94-94f0-da35ec25ccf6.png)

So you can either connect to the postgres database and change this value yourself or you can start refinery and execute the PostgreSQL command directly in the container:
1. find the name of your postgres docker container with ```docker ps``` (for me it is "refinery_graphql-postgres_1", but it might differ for you)
2. execute the following command in your bash: ```$ docker exec NAME_OF_YOUR_POSTGRES_CONTAINER psql -At postgresql://postgres:onetask@graphql-postgres:5432 -c "UPDATE weak_supervision_task SET state = 'FAILED' WHERE state = 'CREATED'"``` 

Explanation: This updates all weak supervision tasks that are still on "CREATED" and sets them to "FAILED".

Hope this resolves your issue. If the weak supervision database state was not the problem, please let us know, so we can work out other solutions!

**Comment by antopolskiy** [comment]
This resolved the issue. Thank you @DerEchteFeuerpfeil ! I really appreciate it
