### ISSUE TITLE
[BUG] - Manually uploaded labels not available when downloading records

### ISSUE THREAD

**Issue by xavialex** [code-kern-ai/refinery#224]
While uploading records with a label (with the format [feature__label]), downloading the records result in null labels. The field is_valid_manual_label is set to false. I'm leaving here a very simple [test.csv](https://github.com/code-kern-ai/refinery/files/10685027/test.csv) to reproduce the behavior. Simply create a project from this file, then Settings -> Download records.

Extra info 
 - OS: M1 MacOS 13.1
 - Browser Chrome
 - Version 109.0.5414.87

See in [Discord](https://discord.com/channels/993436333055938600/1012383333331779716/1072840690997919764)

**Comment by JWittmeyer** [comment]
Hi @xavialex,

looked into it. You are right, the is_valid_manual_label field isn't set correctly for imported labels via the <task>__<label> strucutre. We are already working on a fix. it will however only be part of the next release so not really a help for the existing projects.

For your existing projects we have a few options:
1. (and probably easiest) export the project via project snapshot and reimport it. This should trigger setting the correct value. Please keep in mind that you shouldn't delete the old project file until it's verified that the process worked to ensure your progress isn't lost.
2. (only viable if you have an database browser since doing this via console would be a hassle) I could provide you with an update query though it's quite big.
3. Not sure if you have access to http://localhost:4455/graphql/ (can't check atm). If yes we could work some magic there.


All in all, I would try the first approach and only decide on further steps depending on the result. For your example file this worked without any issues

**Comment by xavialex** [comment]
Hi @JWittmeyer, thanks. Not a real issue since Ibumped into this while making small tests, so I've no projects affected. I'll keep with the CSV files and upload them into new projects when the release takes care of this.
