### ISSUE TITLE
Starting refinery raises KeyError

### ISSUE THREAD

**Issue by krlng** [code-kern-ai/refinery#248]
**Describe the bug**
Basically I only installed refinery and tried to start it. I got:

```
>> refinery start
v1.8.0: Pulling from kernai/alfred
Digest: sha256:15fc59b24103ea7e9bebcbf08df1a76fb269778ed54331d320e3f173eaaaf0f1
Status: Image is up to date for kernai/alfred:v1.8.0
docker.io/kernai/alfred:v1.8.0
def7b07916655d70d9b27d3888001b4b611a9cbe0b30f89fade86dc2dc05afe5
Creating docker-compose.yml file...
Traceback (most recent call last):
  File "/program/start.py", line 31, in <module>
    process_docker_compose_template(refinery_dir, minio_endpoint)
  File "/program/util/template_processor.py", line 17, in process_docker_compose_template
    credential_ip = get_credential_ip()
  File "/program/util/docker_helper.py", line 56, in get_credential_ip
    return network.attrs["IPAM"]["Config"][0]["Gateway"]
KeyError: 'Gateway'
```

**To Reproduce**
Install kern-refinery==1.3.0 and run `refinery start`

**Desktop (please complete the following information):**
Apple M2 Max, macOS 13.3.1

**Comment by JWittmeyer** [comment]
Hi @krlng,

thanks for reaching out. We noticed a similar issue with a different user just recently. There seems to be an issue with the collection of the necessary network address right after the installation (usually because the docker network couldn't be initialized correctly).

The final solution was to restart the computer. 

If that doesn't help could you provide the results of the command `docker network inspect bridge`

**Comment by JWittmeyer** [comment]
Any update @krlng ?

**Comment by JWittmeyer** [comment]
Reopen if the error still occurs
