### ISSUE TITLE
[BUG] - Linebreaks are not displayed correctly in the labeling view

### ISSUE THREAD

**Issue by DerKernigeFeuerpfeil** [code-kern-ai/refinery#256]
**Describe the bug**
I have a pandas dataframe that has an attribute "email" which are full-length E-Mails. These E-Mails have a typical structure with a greeting, a body, an ending and a footer. The nice formatting is achieved with "\n" characters in my Python strings. When I export my data to csv (quoting=1) or to json using the pandas functions and then upload it to refinery, the formatting gets partially lost. The displayed E-Mails are now just a single blob without any linebreaks whatsoever.

After testing with a minimal example, I found that "\n" is displayed correctly, but "\n\n" does not display ANY linebreak at all.

**To Reproduce**
1. Go to refinery
2. Upload my sample data as a new project
3. Create Extraction labeling task
4. Go to labeling view and see error

**Expected behavior**
All linebreaks should be displayed correctly, no matter how many are chained. 

**Screenshots**
![image](https://github.com/code-kern-ai/refinery/assets/125971956/0ff27f37-810c-4273-a67d-7bc66e200f33)

**Desktop (please complete the following information):**
 - OS:  win
 - Browser edge
 - Version: dev-app v1.10.0

**EXAMPLE.json**
```
[{"Summary":"Hello there,\n\nGeneral Kenobi\n\nFOOTER\nFooter2\nFooter3\nFooter4\n\nFooter5"}]
```

**Comment by JWittmeyer** [comment]
Since display pre interpretes whitespace as "this needs to be displayed" we now have the issue that spaces are shown even though no space is present in the record
![image](https://github.com/code-kern-ai/refinery/assets/91723236/c4bd5c93-db1d-4af9-ac56-e472c1697f3d)

I think we need to put the text without any whitespace
![image](https://github.com/code-kern-ai/refinery/assets/91723236/2b347881-8f40-4c61-97d5-d328ee5730c9)

so something like `<span>{somevalue}</span>`

- [ ] resolved
