### ISSUE TITLE
[BUG] - write /var/lib/docker/tmp/GetImageBlob298522289: no space left on device

### ISSUE THREAD

**Issue by epinnock** [code-kern-ai/refinery#266]
**Describe the bug**
Running the start.bat file in window 11 and I'm getting the following results

**To Reproduce**
1. Clone the repo
2. Run Start.bat

**Expected behavior**

**Screenshots**

v1.8.0: Pulling from kernai/alfred
Digest: sha256:15fc59b24103ea7e9bebcbf08df1a76fb269778ed54331d320e3f173eaaaf0f1
Status: Image is up to date for kernai/alfred:v1.8.0
docker.io/kernai/alfred:v1.8.0
docker: Error response from daemon: Conflict. The container name "/alfred" is already in use by container "217992e636f5b57a1ad2fb6fbacbad4fff40881f27a4462545546210c388dc86". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Creating docker-compose.yml file...
Creating jwks.json secret if not existing...
Checking and pulling exec env images...
Starting postgres container...
Creating network "refinery_default" with the default driver
Creating refinery_graphql-postgres_1 ...
Creating refinery_graphql-postgres_1 ... done
Waiting for postgres to be ready...
No revision found
Starting all containers...
Pulling refinery-authorizer (kernai/refinery-authorizer:v1.11.0)...
v1.11.0: Pulling from kernai/refinery-authorizer
write /var/lib/docker/tmp/GetImageBlob298522289: no space left on device

**Desktop (please complete the following information):**
 - OS:Windows 11
 - Browser N/A
 - Version main branch

**Additional context**
the docker containers start but then I get the above error but there is storage space on devcie

**Comment by JWittmeyer** [comment]
Hi @epinnock,

glad you want to try out refinery.

Regarding your provided log there seem to be two issues:
1st `docker: Error response from daemon: Conflict. The container name "/alfred" is already in use by container` 
-> This shouldn't happen on a normal startup. Are you using docker for something else as well? If not did you start the script beforehand? Again if yes you should also run the stop.bat script. 

If everything else fails and you are certain that you don't use docker for something else you can run this command in a cmd shell: `FOR /f "tokens=*" %i IN ('docker ps -qa') DO docker rm -f %i` 
note that this will shut down all docker containers on your system. This doesn't cause issues with none-docker programs or the Operating System. 


The 2nd Error (`write /var/lib/docker/tmp/GetImageBlob298522289: no space left on device`) is a standard docker error for missing space on the hard drive. I found a few online threads discussing the storage location on Windows 11. All of them seem to point towards the C: Drive. The whole application takes up > 10GB storage space depending on your usage. The image files are handled by docker itself, additional data (like your projects, database etc.) is stored in the folder you stated the application from.

Since everyone uses their system a bit differently it's hard to come up with further steps without knowing more. if you want we could also jump into a quick call and look at this together

**Comment by epinnock** [comment]
Hey so I do have enough space, I'll try on a different box to see if I still see the same issue. If not I may have to take you up on that offer of a call

**Comment by jhoetter** [comment]
@epinnock is this one still relevant, i.e. did you try it? Otherwise I'd close it.
