### ISSUE TITLE
[BUG] - Encoding error on downloading arabic letters

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/refinery#89]
**Describe the bug**
When downloading data with arabic letters (see the [data file](https://discord.com/channels/993436333055938600/994293197087969311/1019943186531090442) provided in the context on Discord), the encoding has an erroneous format:

```
\u064a\u0635\u0628\u0631 \u0627\u0644\u0645\u064a\u0645\u062a\u0647\u0627 \u0648\u0627\u0644\u0644\u0647 \u064a\u0631\u062d\u0645 \u0645\u0631\u064a\u0645 \u0648\u064a\u0633\u0643\u0646\u0647\u0627 \u0641\u0633\u064a\u062d \u062c\u0646\u0627\u062a\u0647"
```

**To Reproduce**
Upload said data file and export the data in the UI

**Expected behavior**
Should download the data in correct encoding

**Screenshots**
\-

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 1.2.0

**Additional context**
Asked on [Discord](https://discord.com/channels/993436333055938600/994293197087969311/1019914771593707551) by abdessamad

**Comment by JWittmeyer** [comment]
seems to be a common coding thing for pandas / json export. 
Using the file option should do the trick.
https://stackoverflow.com/a/39612316/19801189

**Comment by jhoetter** [comment]
Awesome, thanks for the suggestion. Will look into this :)

**Comment by JWittmeyer** [comment]
after reading a bit on the benefits of using the byte decode on [stack overflow](https://stackoverflow.com/a/594881/19801189) it seems that the utf-8 should be useable by all readers. Since we now switched to a different export procedure with [this](https://github.com/code-kern-ai/refinery/issues/143) issue I see no problem in using the utf-8 version. 

will be included in the next release.
