### ISSUE TITLE
[BUG] - Filter by weak supervision confidence in 2 tasks

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/refinery#97]
**Describe the bug**
I have one classification and one extraction task, for which I have weak supervision labels for both. Now, when I want to filter for low confidence records of task A, task B scores are also considered. This makes it much harder for me to find low-quality records of task A.

**To Reproduce**
I will provide a sample project as a zip file which you can import as a local snapshot. Generally, the steps are:
1. Create a project with two labeling tasks
2. Create weakly supervised labels for both
3. Try filtering for the confidence score; you will see that this filter is always applied on both tasks

**Expected behavior**
Only filter the confidence of the selected task (i.e. the one which's drawer is open)

**Screenshots**
![image](https://user-images.githubusercontent.com/62521561/191229108-b73efbbf-0ac5-435c-a1b5-9949f5a57b56.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 1.2.0

**Additional context**
\-

**Comment by jhoetter** [comment]
[project_export_2022_09_20_11_25_13.zip](https://github.com/code-kern-ai/refinery/files/9607239/project_export_2022_09_20_11_25_13.zip)

**Comment by JWittmeyer** [comment]
This seems to be already fixed - the provided project doesn't yield the same results (less items filtered & scrolling testing with static slice + db query didn't show anything with higher confidence than 0.2959740681299307)

Best quess: Fixed by the confidence issue https://github.com/code-kern-ai/refinery/issues/99 - missing grouping in prepared query

PR that fixed it: https://github.com/code-kern-ai/refinery-gateway/pull/65
